# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamNumber', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('autoPoints', models.IntegerField()),
                ('year', models.IntegerField(default=2017)),
                ('tasks', models.ManyToManyField(to='tasks.Task')),
            ],
        ),
    ]
