# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='autoPoints',
            new_name='auto_points',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='teamNumber',
            new_name='team_number',
        ),
    ]
