# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20170207_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
