# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('team_number', 'year')]),
        ),
    ]
