# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20170210_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='tasks.Task'),
        ),
    ]
