# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-12 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20170210_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='auto_points',
            field=models.IntegerField(default=0),
        ),
    ]
